version: "3.5"
services:
  postgres:
   volumes: 
      - postgres_api_data:/data/postgres
  hackio-ms:
    command: npm run start:debug
    volumes: 
      - ./hackio-ms/:/usr/src/app
      - hackio_modules:/usr/src/app/node_modules            
volumes:
  postgres_api_data: {}
  hackio_modules: {}
