version: "3.5"
services:
  nginx:
    image: nginx:1.11
    ports:
      - 88:80
      - 443:443
    depends_on:
      - gatekeeper-ms
      - hackio-ms
    networks:
      - hackio-network
  postgres:
    image: postgres
    ports:
      - 5438:5432
    volumes:
      - postgres_api_data:/data/postgres
    restart: always
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    networks:
      - hackio-network
  hackio-ms:
    build: ./hackio-ms/
    image: hackio-ms
    container_name: hackio_ms
    depends_on:
      - postgres
    networks:
      - hackio-network   
  gatekeeper-ms:
    build: ./gatekeeper-ms/
    image: gatekeeper-ms
    container_name: gatekeeper_ms
    networks:
      - hackio-network      
networks:
  hackio-network:
    driver: bridge
    name: hackio-network
