version: "3.5"
services:
  postgres:
   volumes: 
      - postgres_api_data:/data/postgres
  hackio-ms:
   container_name: hackio_ms
   command: npm run start:debug
   environment:
     NPM_INSTALL: ENABLE
     TYPEORM_MIGRATION: ENABLE
   ports:
     - 4000:3000
     - 5858:5858
   volumes:
     - ./hackio-ms:/app

volumes:
  postgres_api_data: {}
  hackio_modules: {}
