version: "3.5"
services:
  nginx:
    volumes:
      - ./proxy/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./proxy/ssl:/etc/nginx/ssl:ro
  postgres:
   volumes: 
      - postgres_api_data:/data/postgres
  hackio-ms:
   container_name: hackio_ms
   command: npm run start:debug
   environment:
     NPM_INSTALL: ENABLE
     TYPEORM_MIGRATION: ENABLE
   ports:
     - 4000:3000
     - 5800:5858
   volumes:
     - ./hackio-ms:/app
  gatekeeper-ms:
   container_name: gatekeeper_ms
   command: npm run start:debug
   environment:
     NPM_INSTALL: ENABLE
     TYPEORM_MIGRATION: ENABLE
   ports:
     - 4002:3000
     - 5820:5858
   volumes:
     - ./gatekeeper-ms:/app
volumes:
  postgres_api_data: {}
  hackio_modules: {}
  gatekeeper_modules: {}
