version: "3.5"
services:
  postgres:
    image: postgres
    ports:
      - 5436:5432
    volumes:
      - postgres_api_data:/data/postgres
    restart: always
    environment:
      POSTGRES_DB: admin
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      PGDATA: /data/postgres
    networks:
      - hackio-network
  hackio-ms:
    build: ./hackio-ms/
    image: hackio-ms
    container_name: hackio_ms
    environment:
      - NODE_ENV=local
    ports:
      - 4000:3000
      - 5858:5858
    depends_on:
      - postgres
    networks:
      - hackio-network     
networks:
  hackio-network:
    driver: bridge
    name: hackio-network
