FROM node:12-buster-slim

WORKDIR /app

COPY package.json package-lock.json /app/

RUN npm install && \
  rm -rf /tmp/* /var/tmp/*

COPY . /app

RUN npm run build

EXPOSE 3000

USER node

CMD npm run migration:run
CMD npm run start:prod
